server:
  port: 8082

spring:
  application:
    name: member-service

  datasource:
    url: jdbc:postgresql://localhost:5432/tenten
    username: postgres
    password: 19pool90

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none

  liquibase:
    change-log: 'classpath:/db/changelog/liquibase.change-log.xml'

  logging:
    level:
      root: INFO
      com.example.demo_resource_server: DEBUG
      org.springframework.jdbc: DEBUG
      org.springframework.security: trace

openapi:
  service:
    title: member-service doc
    version: 1.0.0
    url: http://127.0.0.1:8080

springdoc:
  api-docs:
    path: /member-service/v3/api-docs
  swagger-ui:
    path: /member-service/swagger-ui.html

#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#  instance:
#    hostname: localhost

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
  instance:
    hostname: member-service