server:
  port: 8080

spring:
#  security:
#    oauth2:
#      resourceserver:
#        opaquetoken:
#          introspection-uri: http://localhost:8081/oauth2/introspect
#          client-id: browser-client
#          client-secret: secret
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      httpclient:
        connect-timeout: 20000
        response-timeout: 7s
      routes:

        - id: doctor-service
          uri: lb://doctor-service
          predicates:
            - Path=/departments/** , /doctor-service/v3/api-docs , /bookings/**

        - id: member-service
          uri: lb://member-service
          predicates:
            - Path=/patients/** , /member-service/v3/api-docs

        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/auditReport/** , /notification-service/v3/api-docs

        - id: user-management-service
          uri: lb://user-management-service
          predicates:
            - Path=/users/** , /user-management-service/v3/api-docs

springdoc:
  enable-native-support: true
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: API Gateway Service
        primaryName: API Gateway Service

      - url: /doctor-service/v3/api-docs
        name: Doctor Service
        primaryName: Doctor Service

      - url: /member-service/v3/api-docs
        name: Member Service
        primaryName: Member Service

      - url: /notification-service/v3/api-docs
        name: Notification Service
        primaryName: Notification Service

      - url: /user-management-service/v3/api-docs
        name: User Management Service
        primaryName: User management Service

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/