server:
  servlet:
    context-path: /
  port:
    8085

spring:
  application:
    name: doctor-service

  datasource:
    url: jdbc:postgresql://localhost:5432/tenten
    username: postgres
    password: 19pool90

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none

  cloud:
    loadbalancer:
      ribbon:
        enabled: false

    bootstrap:
      enabled: true

  liquibase:
    change-log: 'classpath:/db/changelog/liquibase.change-log.xml'

  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: 'false'

  zipkin:
    base-url: http://zipkin:9411/api/v2/spans
  sleuth:
    sampler:
      probability: 1.0

openapi:
  service:
    title: doctor-service doc
    version: 1.0.0
    url: http://localhost:8080

springdoc:
  api-docs:
    path: /doctor-service/v3/api-docs
  swagger-ui:
    path: /doctor-service/swagger-ui.html

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
  instance:
    hostname: doctor-service

management:
  endpoints:
    web:
      exposure:
        include: prometheus

#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#  instance:
#    hostname: localhost
